### ISSUE TITLE
Wrong Node Module name after extraction

### ISSUE THREAD

**Issue by ilucker** [webjars/webjars-locator-core#12]
if a module name is not the first name attribute in the package.json, the module is extracting with the wrong name. 

E.g. the module [util](https://github.com/defunctzombie/node-util) declares the author's name "Joyent" before the module name and after extraction the module has a name "Joyent" instead of "util".

You can use https://github.com/ilucker/webjars-node-extract to reproduce the issue. 
Run `>sbt web-assets:webJarsNodeModules` and check `/target/web/node-modules/main/webjars`

**Comment by jamesward** [comment]
I'm not sure I understand this.  Can you provide more details?

**Comment by ilucker** [comment]
I have a project (see https://github.com/ilucker/webjars-node-extract for example). In this project i use a npm module [util](https://github.com/defunctzombie/node-util) packed in the webjar.   

I expect that WebJarExtractor will extract this module to a folder named "util" but it extracts it to a folder named Joyent (run `sbt web-assets:webJarsNodeModules` and check  `/target/web/node-modules/main/webjars`). 

I assume this is because in the attribute `actor.name` from the [package.json](https://github.com/defunctzombie/node-util/blob/master/package.json) file is coming before the top-level attribute `name` and WebJarExtractor uses `actor.name` instead of the `name`

**Comment by jamesward** [comment]
Ah. We don't have any control over that.  You'll need to file an issue with: https://github.com/sbt/sbt-web

**Comment by ilucker** [comment]
@jamesward i don't think so. The problem in in the implementation of me method [getJsonNodeModuleId](https://github.com/webjars/webjars-locator-core/blob/master/src/main/java/org/webjars/WebJarExtractor.java#L323) and method extractAllNodeModulesTo(file) is working incorrect.

**Comment by jamesward** [comment]
@ilucker Wow.  I didn't realize this was in here.  Sorry about that.  I'll take a look.

**Comment by yuchi** [comment]
Also may I suggest **not to** use string searching for json values extraction and use for example JSONPath? *package.json* files very often uses an extended schema.

**Comment by jamesward** [comment]
Yeah! I was shocked seeing that.  I think maybe it was done that way to reduce deps and prevent dep collisions.  So I'll have to decide on a JSON parser to go with.

**Comment by yuchi** [comment]
The issue is you don't need it fully parsed. I'm pretty sure you can find a stream based with path collector one.

**Comment by jamesward** [comment]
Here is the PR with a fix: https://github.com/webjars/webjars-locator-core/pull/13

I decided to use `jackson-databind` for JSON parsing since that is what `webjars-locator` uses.

**Comment by jamesward** [comment]
This is being released as `0.31`.  Let me know if that fixes the issue.

**Comment by ilucker** [comment]
Thank you. It works for me.
