### ISSUE TITLE
Why 0.57 release?

### ISSUE THREAD

**Issue by mkurz** [webjars/webjars-locator-core#146]
@jamesward Why did you release 0.57, it seems there is not difference?

https://github.com/webjars/webjars-locator-core/compare/webjars-locator-core-0.56...webjars-locator-core-0.57

**Comment by mkurz** [comment]
Releases are almost the same on maven central, just 2 bytes difference in the jar:
- https://repo1.maven.org/maven2/org/webjars/webjars-locator-core/0.56/
- https://repo1.maven.org/maven2/org/webjars/webjars-locator-core/0.57/

POM's are basically the same:
- https://repo1.maven.org/maven2/org/webjars/webjars-locator-core/0.56/webjars-locator-core-0.56.pom
- https://repo1.maven.org/maven2/org/webjars/webjars-locator-core/0.57/webjars-locator-core-0.57.pom

**Comment by jamesward** [comment]
Whoops.  Thanks for catching this.  The problem was that my local branch was still using `master` so I'm doing a `0.58` release that is from the correct branch. https://github.com/webjars/webjars-locator-core/compare/webjars-locator-core-0.56...webjars-locator-core-0.58
