### ISSUE TITLE
Infinite loop extracting certain webjars

### ISSUE THREAD

**Issue by spencerhakim** [webjars/webjars-locator-core#30]
The recent refactor in 60f01fb609844cbe7d6d39055e756bd13e35a9fb, released in v0.39, contains a bug ([this `equals`](https://github.com/webjars/webjars-locator-core/blob/c75a9be6069c4627ece4d3f7f7e2336387f2a0f1/src/main/java/org/webjars/WebJarExtractor.java#L279) became [this `endsWith`](https://github.com/webjars/webjars-locator-core/blob/b9b1dcaa491396b1f1676f37397822543289e28d/src/main/java/org/webjars/WebJarExtractor.java#L99)) which exposed another bug in [`WebJarExtractor#getJsonModuleId`](https://github.com/webjars/webjars-locator-core/blob/b9b1dcaa491396b1f1676f37397822543289e28d/src/main/java/org/webjars/WebJarExtractor.java#L188-L196) where a `package.json` missing the `name` field will result in an infinite loop. This wasn't an issue before the refactor because only the primary `package.json` would be parsed, but after the refactor _any_ `package.json` in the webjar is parsed.

For example, I ran into this issue with `@angular/http@2.4.10`, which contains a secondary `package.json` which should be ignored:

`META-INF/resources/webjars/angular__http/2.4.10/testing/package.json`
```json
{"main": "../bundles/http-testing.umd.js"}
```

**Comment by jamesward** [comment]
Whoops!  Thanks for reporting.  I'm working on this now.

**Comment by jamesward** [comment]
I'm releasing `0.40` now with a fix.  There is still some nastiness under the covers that I'll fix later.

**Comment by spencerhakim** [comment]
Thanks for fixing this quickly, appreciate it!
