### ISSUE TITLE
MultipleMatchesException since 0.37 on WildFly

### ISSUE THREAD

**Issue by jvs64893** [webjars/webjars-locator-core#35]
Starting with webjars-locator 0.37 I get errors on my project in WildFly 18.0.1.

These are my dependencies:
```
implementation group: 'org.webjars', name: 'webjars-locator', version: '0.38'
implementation group: 'org.webjars', name: 'webjars-locator-jboss-vfs', version: '0.1.0'
implementation group: 'org.webjars.npm', name: 'swagger-ui-dist', version: '3.25.0'
```

When accessing a file I get a MultipleMatchesException:
```
org.webjars.MultipleMatchesException: Multiple matches found for favicon-16x16.png. Please provide a more specific path, for example by including a version number.
	at org.webjars.WebJarAssetLocator.throwMultipleMatchesException(WebJarAssetLocator.java:182)
	at org.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:238)
```

Example code I use:
```
WebJarAssetLocator locator = new WebJarAssetLocator();
locator.getFullPath("swagger-ui-dist", "favicon-16x16.png");
```

Everything works fine if I use webjars-locator 0.36.

If you need any more information please let me know.

**Comment by jamesward** [comment]
Thanks for reporting.  I'm trying to reproduce this but not able to.  Can do a clean to make sure there isn't something else on the classpath causing this?
Also, I don't think you need `webjars-locator-jboss-vfs` any longer.  Maybe that is causing something to go wrong.

**Comment by jvs64893** [comment]
I removed the `webjars-locator-jboss-vfs`, but this didn't change anything. I tried to debug this a bit further and it seems that the content of the webjar is added twice.

Here is a screenshot of the variables when I put a breakpoint on getFullPath():
![Webjar](https://user-images.githubusercontent.com/47816770/74716172-51a59200-522e-11ea-9a0b-d51bf1928ca6.png)
As you can see, every entry is added twice.

Does this already help you track down the issue or do you need some more information?

**Comment by jamesward** [comment]
Strange.  Somehow the way your build is formulating the classpath it must be duplicating a JAR entry.  But I think that we should remove duplicate entries so I'll work on that.

**Comment by jamesward** [comment]
I'm releasing `webjars-locator-core` version `0.44` now that will hopefully remove these duplicates.
