### ISSUE TITLE
Consider upgrading io.github.classgraph:classgraph to resolve security issue

### ISSUE THREAD

**Issue by ciscoo** [webjars/webjars-locator-core#40]
My company's internally hosted Nexus IQ (Lifecycle) is flagging `io.github.classgraph:classgraph:4.8.106` as vulnerable. I tracked it down to `webjars-locator-core`:

https://github.com/webjars/webjars-locator-core/blob/5708ab1e74050c51ed9fbf3698ce95ff86810519/pom.xml#L57

It seems versions < 4.8.112 are vulnerable to the following:

* https://github.com/classgraph/classgraph/pull/539
* https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.112

As a workaround (Gradle platform) I am doing the following:

```groovy

dependencies {
    constraints {
        api("io.github.classgraph:classgraph") {
            version {
                require("4.8.112")
            }
            because("Lower versions have a critical security vulnerability.")
        }
    }
}
```

Please consider upgrading the vulnerable dependency and releasing a new version for `webjars-locator-core` and all dependencies that depend on it such as `webjars-locator`

**Comment by jamesward** [comment]
Thanks for the heads up. `webjars-locator` `0.42` will be released shortly which has `webjars-locator-core` `0.48` which has `classgraph` `4.8.115`
