### ISSUE TITLE
Web page cannot resolve jQuery 3.6.0 without the version number in path

### ISSUE THREAD

**Issue by sdrkyj** [webjars/webjars-locator-core#76]
As the title described, web page cannot resolve jQuery 3.6.0 without the version number in path. 
In a HTML page, <script> tag
`/webjars/jquery/3.6.0/dist/jquery.min.js`
works, but
`/webjars/jquery/dist/jquery.min.js`
returns 404

**Comment by jamesward** [comment]
This is by design to support good caching.  Some frameworks provide a way to use the version-less paths but that is a framework specific thing.

**Comment by sdrkyj** [comment]
Integrated using Spring boot 2.6.7. Other webjar libraries referenced without version numbers work fine, except jQuery 3.6.0.
So is that the problem of spring boot framework ?
